install-and-test: &install-and-test
  - checkout
  - restore_cache:
      key: node-modules-{{ checksum "package-lock.json" }}
  - run: npm install
  - save_cache:
      key: node-modules-{{ checksum "package-lock.json" }}
      paths:
        - node_modules
  - run: npm test

version: 2.1
jobs:
  test-node-20: # Maintenance, EOL 2026.04.30
    docker:
      - image: cimg/node:20.19
    steps:
      *install-and-test
  test-node-22: # LTS, EOL 2027.04.30
    docker:
      - image: cimg/node:22.17
    steps:
      *install-and-test
  test-node-24: # Current, EOL 2028.04.30
    docker:
      - image: cimg/node:24.4
    steps:
      *install-and-test
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      # install & test just in case we have overlooked to bump node versions
      # above, and cimg/node:lts is not just an alias to one of the environments
      # where we have tested it.
      - run: npm install
      - run: npm test

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

test-filters: &test-filters
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - test-node-20:
          <<: *test-filters
      - test-node-22:
          <<: *test-filters
      - test-node-24:
          <<: *test-filters
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - test-node-20
            - test-node-22
            - test-node-24
