version: 2
jobs:
  test-node-16: # Maintenance, EOL 2023.09.11
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - restore_cache:
          key: node-modules-16-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-16-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  test-node-18: # LTS, EOL 2025.04.30
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - restore_cache:
          key: node-modules-18-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-18-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  test-node-20: # Current, EOL 2026.04.30
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout
      - restore_cache:
          key: node-modules-20-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-20-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      # install & test just in case we have overlooked to bump node versions
      # above, and cimg/node:lts is not just an alias to one of the environments
      # where we have tested it.
      - run: npm install
      - run: npm test

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

test-filters: &test-filters
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - test-node-16:
          <<: *test-filters
      - test-node-18:
          <<: *test-filters
      - test-node-20:
          <<: *test-filters
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - test-node-16
            - test-node-18
            - test-node-20
